# Generated by Django 4.2.4 on 2023-08-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRegistrationForm', '0002_remove_userprofile_username_userprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sub',
            field=models.TextField(default='blank'),
            preserve_default=False,
        ),
    ]
