# Generated by Django 4.2.4 on 2023-08-25 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRegistrationForm', '0003_userprofile_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='select_class',
            field=models.CharField(blank=True, choices=[('class i', 'Class I'), ('class ii', 'Class II'), ('class iii', 'Class III'), ('class iv', 'Class IV'), ('class v', 'Class V'), ('class vi', 'Class VI'), ('class vii', 'Class VII'), ('class viii', 'Class VIII'), ('class ix', 'Class IX'), ('class x', 'Class X'), ('class xi', 'Class XI'), ('class xii', 'Class XII')], max_length=12, null=True),
        ),
    ]
